-- =====================================================
-- On-Chain News Provider - Supabase Schema
-- Run this in your Supabase SQL Editor
-- =====================================================

-- 1. Tokens Registry Table
CREATE TABLE IF NOT EXISTS tokens (
    id TEXT PRIMARY KEY,           -- Token slug (e.g., "bitcoin", "ethereum")
    name TEXT NOT NULL,            -- Display name
    enabled BOOLEAN DEFAULT TRUE,  -- Whether to scrape this token
    scrape_interval INT DEFAULT 60, -- Minutes between scrapes
    last_scraped TIMESTAMPTZ,      -- Last successful scrape time
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Insights Table (with sources)
-- If you already have an insights table, run this ALTER instead:
-- ALTER TABLE insights ADD COLUMN IF NOT EXISTS token_id TEXT;
-- ALTER TABLE insights ADD COLUMN IF NOT EXISTS sources JSONB DEFAULT '[]'::jsonb;

CREATE TABLE IF NOT EXISTS insights (
    id TEXT PRIMARY KEY,
    token_id TEXT,                 -- Which token this insight belongs to
    timestamp BIGINT,
    title TEXT,
    content TEXT,
    source_count INT DEFAULT 0,
    sources JSONB DEFAULT '[]'::jsonb,  -- Array of {url, title} objects
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create index for faster queries by token
CREATE INDEX IF NOT EXISTS idx_insights_token_id ON insights(token_id);
CREATE INDEX IF NOT EXISTS idx_insights_timestamp ON insights(timestamp DESC);

-- 3. Scraper State Table
CREATE TABLE IF NOT EXISTS scraper_state (
    key TEXT PRIMARY KEY,
    value TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- API Platform Tables
-- =====================================================

-- 4. Users (Wallet Addresses)
CREATE TABLE IF NOT EXISTS users (
    address TEXT PRIMARY KEY,      -- Wallet address (lowercase)
    nonce TEXT,                    -- For SIWE verification
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_login TIMESTAMPTZ
);

-- 5. API Keys
CREATE TABLE IF NOT EXISTS api_keys (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_address TEXT REFERENCES users(address) ON DELETE CASCADE,
    key_hash TEXT NOT NULL,        -- Hashed API key (never store plain)
    name TEXT,                     -- e.g., "Prod App", "Test"
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_used_at TIMESTAMPTZ
);

-- 6. Credits & Usage
CREATE TABLE IF NOT EXISTS credits (
    user_address TEXT PRIMARY KEY REFERENCES users(address) ON DELETE CASCADE,
    balance INT DEFAULT 100,       -- Free tier start
    plan_type TEXT DEFAULT 'free', -- free, starter, pro, enterprise
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key_id UUID REFERENCES api_keys(id),
    user_address TEXT REFERENCES users(address),
    endpoint TEXT,
    status_code INT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Payments History
CREATE TABLE IF NOT EXISTS payments (
    tx_hash TEXT PRIMARY KEY,
    user_address TEXT REFERENCES users(address),
    amount_usdc DECIMAL,
    credits_added INT,
    chain_id INT DEFAULT 8453,     -- Base Mainnet
    status TEXT DEFAULT 'pending', -- pending, confirmed, failed
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_api_keys_user ON api_keys(user_address);
CREATE INDEX IF NOT EXISTS idx_usage_user ON usage_logs(user_address);
CREATE INDEX IF NOT EXISTS idx_usage_created_at ON usage_logs(created_at DESC);

-- =====================================================
-- Seed Initial Tokens (optional - customize as needed)
-- =====================================================
INSERT INTO tokens (id, name, enabled, scrape_interval) VALUES
    ('ethereum', 'Ethereum', TRUE, 60),
    ('bitcoin', 'Bitcoin', TRUE, 60),
    ('solana', 'Solana', TRUE, 60)
ON CONFLICT (id) DO NOTHING;
